import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 13.0
# normal = { family = "MesloLGS NF", style = "Regular" }
# bold = { family = "MesloLGS NF", style = "Bold" }
# italic = { family = "MesloLGS NF", style = "Italic" }
# bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

